name: "Data Protection Officer"
endpoints:
- endpoint: /admin/v1/groups
  methods:
  - GET
- endpoint: "/admin/v1/groups/*"
  methods:
  - GET
- endpoint: "/admin/v1/groups/*/users"
  methods:
  - GET
  - POST
- endpoint: "/admin/v1/groups/*/users/*"
  methods:
  - GET
  - PATCH
  - DELETE
- endpoint: /admin/v1/users
  methods:
  - GET
- endpoint: "/admin/v1/users/*"
  methods:
  - GET
  - PATCH
- endpoint: /composite/v1/composite
  methods:
  - POST
- endpoint: /composite/v1/openapi.json
  methods:
  - GET
accessibleFields:
  "*":
    edit:
    - "*public"
    - "*internal"
    view:
    - "*public"
    - "*internal"
  User:
    edit:
    - "*public"
    - "*internal"
    - roles
    view:
    - "*public"
    - "*internal"
    - authorityLimitProfile
    - authorityLimitProfileId
    - authorityLimitProfileName
    - roles