swagger: "2.0"
x-gw-cors-policies:
  admin:
    enabled: "${cors.claims.enabled:true}"
    allowOrigins: "${cors.claims.allowOrigins:any}"
    allowCredentials: "${cors.claims.allowCredentials:true}"
    allowHeaders: "${cors.claims.allowHeaders:null}"
    exposeHeaders: "${cors.claims.exposeHeaders:null}"
    maxAge: "${cors.claims.maxAge:1200}"
    allowMethods: "${cors.claims.allowMethods:null}"
  claims:
    enabled: "${cors.claims.enabled:true}"
    allowOrigins: "${cors.claims.allowOrigins:any}"
    allowCredentials: "${cors.claims.allowCredentials:true}"
    allowHeaders: "${cors.claims.allowHeaders:null}"
    exposeHeaders: "${cors.claims.exposeHeaders:null}"
    maxAge: "${cors.claims.maxAge:1200}"
    allowMethods: "${cors.claims.allowMethods:null}"
  common:
    enabled: "${cors.common.enabled:true}"
    allowOrigins: "${cors.common.allowOrigins:any}"
    allowCredentials: "${cors.common.allowCredentials:true}"
    allowHeaders: "${cors.common.allowHeaders:null}"
    exposeHeaders: "${cors.common.exposeHeaders:null}"
    maxAge: "${cors.common.maxAge:1200}"
    allowMethods: "${cors.common.allowMethods:null}"
  composite:
    enabled: "${cors.composite.enabled:true}"
    allowOrigins: "${cors.composite.allowOrigins:any}"
    allowCredentials: "${cors.composite.allowCredentials:true}"
    allowHeaders: "${cors.composite.allowHeaders:null}"
    exposeHeaders: "${cors.composite.exposeHeaders:null}"
    maxAge: "${cors.composite.maxAge:1200}"
    allowMethods: "${cors.composite.allowMethods:null}"