<%
uses com.guidewire.apd.model.generate.generators.templates.TemplateConfig
%>
<%@ params( contentType: TemplateConfig.ContentType ) %>
${contentType.OpenComment} WARNING! This file was generated by APD. Do not modify this file directly as any changes will be overwritten if the product is re-generated. ${contentType.CloseComment}